[workspace]
resolver = "3"
members = ["macros"]

[package]
name = "towerdefense"
version = "0.1.0"
edition = "2024"

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking", "bevy/file_watcher"]
macro_debug = ["macros/macro_debug"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.19", default-features = false, features = ["2d", "ui", "jpeg", "system_clipboard"] }
macros = { path = "./macros" }
image = "0.25.10"

[target.'cfg(target_os = "linux")'.dependencies]
bevy = { version = "0.19", default-features = false, features = ["wayland"] }
