[workspace]
resolver = "3"
members = ["map_parsing"]

[package]
name = "towerdefense"
version = "0.1.0"
edition = "2024"

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking", "bevy/file_watcher"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.19", default-features = false, features = ["2d", "ui", "jpeg"] }
rand = "0.10.2"
